# Generated by Django 5.0.1 on 2024-01-19 07:01

import base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeofwords',
            name='image',
            field=models.ImageField(upload_to=base.services.path_theme_image, verbose_name='Фото темы'),
        ),
    ]
